### ISSUE TITLE
Создать информационный попап

### ISSUE THREAD

**Issue by DocMoro** [LitVi74/characters-frontend#11]
Попап будет, например, сигнализировать об отправке активационного письма на почту. Если в bootstrap не найдётся подходящий компонент - делегировать.

Стейт - объект поднять в app
{
isShow: boolean,
text: string
}

**Comment by LitVi74** [comment]
можно попробовать Alert https://react-bootstrap.github.io/components/alerts/

**Comment by LitVi74** [comment]
Реализованно через тосты бутстрапа, поднимать общий стейт до App не потребовалось
